// <auto-generated />
using ENOMVG_SOF_2023242.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ENOMVG_SOF_2023242.Migrations
{
    [DbContext(typeof(SchollingDbContext))]
    [Migration("20240625194131_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ENOMVG_SOF_2023242.Models.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("ImageFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Schools");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 0,
                            ImageFileName = "",
                            Name = "Soproni Széchenyi István Gimnázium",
                            Type = 2
                        },
                        new
                        {
                            Id = 2,
                            Age = 0,
                            ImageFileName = "",
                            Name = "Berzsenyi Dániel Evangélikus (Líceum) Gimnázium és Kollégium",
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            Age = 0,
                            ImageFileName = "",
                            Name = "Soproni Deák Téri Általános Iskola",
                            Type = 0
                        });
                });

            modelBuilder.Entity("ENOMVG_SOF_2023242.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<double>("GradesAVG")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 16,
                            GradesAVG = 5.0,
                            Name = "Bejó Mátyás",
                            SchoolId = 1
                        },
                        new
                        {
                            Id = 2,
                            Age = 17,
                            GradesAVG = 3.2400000000000002,
                            Name = "Szojka Áron",
                            SchoolId = 1
                        },
                        new
                        {
                            Id = 3,
                            Age = 17,
                            GradesAVG = 4.7599999999999998,
                            Name = "Hargitai Benke",
                            SchoolId = 2
                        },
                        new
                        {
                            Id = 4,
                            Age = 13,
                            GradesAVG = 4.4530000000000003,
                            Name = "Dejó Dorka",
                            SchoolId = 3
                        });
                });

            modelBuilder.Entity("ENOMVG_SOF_2023242.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("MainSubject")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MainSubject = 0,
                            Name = "Zsoldos Gyöngyi",
                            Salary = 270000,
                            SchoolId = 3
                        },
                        new
                        {
                            Id = 2,
                            MainSubject = 0,
                            Name = "Márti néni",
                            Salary = 245330,
                            SchoolId = 3
                        },
                        new
                        {
                            Id = 3,
                            MainSubject = 2,
                            Name = "Lang",
                            Salary = 400000,
                            SchoolId = 1
                        },
                        new
                        {
                            Id = 4,
                            MainSubject = 3,
                            Name = "Jakab",
                            Salary = 431000,
                            SchoolId = 1
                        },
                        new
                        {
                            Id = 5,
                            MainSubject = 1,
                            Name = "Kovács Antal József",
                            Salary = 220000,
                            SchoolId = 2
                        },
                        new
                        {
                            Id = 6,
                            MainSubject = 5,
                            Name = "Kiss Egér",
                            Salary = 298000,
                            SchoolId = 2
                        });
                });

            modelBuilder.Entity("ENOMVG_SOF_2023242.Models.Student", b =>
                {
                    b.HasOne("ENOMVG_SOF_2023242.Models.School", "School")
                        .WithMany("Students")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("ENOMVG_SOF_2023242.Models.Teacher", b =>
                {
                    b.HasOne("ENOMVG_SOF_2023242.Models.School", "School")
                        .WithMany("Teachers")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("ENOMVG_SOF_2023242.Models.School", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("Teachers");
                });
#pragma warning restore 612, 618
        }
    }
}
